FROM bitnami/spark:3.5.2

COPY requirements/pyspark_requirements.txt /opt/bitnami/spark/requirements/pyspark_requirements.txt
RUN python -m pip install -U pip setuptools && pip install --upgrade pip && pip install --no-cache-dir -r /opt/bitnami/spark/requirements/pyspark_requirements.txt